/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * https://pikadoc.readthedocs.io/zh/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#include "PikaMain.h"
#include <stdio.h>
#include <stdlib.h>

PikaObj *__pikaMain;
PikaObj *pikaScriptInit(void){
    __platform_printf("======[pikascript packages installed]======\r\n");
    pks_printVersion();
    __platform_printf("PikaStdLib==latest\r\n");
    __platform_printf("===========================================\r\n");
    __pikaMain = newRootObj("pikaMain", New_PikaMain);
    extern unsigned char pikaModules_py_a[];
    obj_linkLibrary(__pikaMain, pikaModules_py_a);
#if PIKA_INIT_STRING_ENABLE
    obj_run(__pikaMain,
            "import pika_lvgl as lv\n"
            "import PikaStdLib\n"
            "mem = PikaStdLib.MemChecker()\n"
            "#\n"
            "# Using the text style properties\n"
            "#\n"
            "style = lv.style_t()\n"
            "style.init()\n"
            "style.set_radius(5)\n"
            "style.set_bg_opa(lv.OPA.COVER)\n"
            "style.set_bg_color(lv.palette_lighten(lv.PALETTE.GREY, 3))\n"
            "style.set_border_width(2)\n"
            "style.set_border_color(lv.palette_main(lv.PALETTE.BLUE))\n"
            "style.set_pad_all(10)\n"
            "style.set_text_color(lv.palette_main(lv.PALETTE.BLUE))\n"
            "style.set_text_letter_space(5)\n"
            "style.set_text_line_space(20)\n"
            "style.set_text_decor(lv.TEXT_DECOR.UNDERLINE)\n"
            "# Create an object with the new style\n"
            "obj = lv.label(lv.scr_act())\n"
            "obj.add_style(style, 0)\n"
            "obj.set_text(\"Text of\\n\"\n"
            "             \"a label\")\n"
            "obj.center()\n"
            "\n");
#else 
    obj_runModule(__pikaMain, "main");
#endif
    return __pikaMain;
}

