/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * https://pikadoc.readthedocs.io/zh/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#include "PikaMain.h"
#include <stdio.h>
#include <stdlib.h>

PikaObj *__pikaMain;
PikaObj *pikaScriptInit(void){
    __platform_printf("======[pikascript packages installed]======\r\n");
    pks_printVersion();
    __platform_printf("PikaStdLib==latest\r\n");
    __platform_printf("===========================================\r\n");
    __pikaMain = newRootObj("pikaMain", New_PikaMain);
    extern unsigned char pikaModules_py_a[];
    obj_linkLibrary(__pikaMain, pikaModules_py_a);
#if PIKA_INIT_STRING_ENABLE
    obj_run(__pikaMain,
            "import pika_lvgl as lv\n"
            "import PikaStdLib\n"
            "mem = PikaStdLib.MemChecker()\n"
            "class DataBinding:\n"
            "    _inner_ = []\n"
            "    def __init__(self, data):\n"
            "        _bindings_ = {}\n"
            "        self._inner_.append(_bindings_)\n"
            "        self._inner_.append(data)\n"
            "    def __getattr__(self, name):\n"
            "        data = self._inner_[1]\n"
            "        return data[name]\n"
            "    def __setattr__(self, name, value):\n"
            "        _bindings_ = self._inner_[0]\n"
            "        if name in _bindings_:\n"
            "            bindings = _bindings_[name]\n"
            "            for binding in bindings:\n"
            "                element = binding['element']\n"
            "                attr = binding['attr']\n"
            "                _name = attr.replace(\"-\", \"_\")\n"
            "                funcName = \"set_%s\" % _name\n"
            "                print(funcName, hasattr(element, funcName))\n"
            "                if hasattr(element, funcName):\n"
            "                    func = getattr(element, funcName)\n"
            "                    func(value)\n"
            "                else:\n"
            "                    if hasattr(element, \"obj\") and element.obj:\n"
            "                        setattr(element.obj, _name, value)\n"
            "    def set_binding_value(self, element, attr, key):\n"
            "        _bindings_ = self._inner_[0]\n"
            "        if key not in _bindings_:\n"
            "            _bindings_[key] = []\n"
            "        _bindings_[key].append({\n"
            "            \"element\": element,\n"
            "            \"attr\": attr\n"
            "        })\n"
            "data = {\"clickcount\":0,\"result\":\"\",\"count\":0}\n"
            "data = DataBinding(data)\n"
            "widget0 = lv.obj(lv.scr_act())\n"
            "style = lv.style_t()\n"
            "style.init()\n"
            "widget0.set_width(240)\n"
            "widget0.set_height(240)\n"
            "style.set_bg_color(lv.lv_color_hex(37864))\n"
            "widget0.add_style(style, 0)\n"
            "widget1 = lv.label(widget0)\n"
            "style = lv.style_t()\n"
            "style.init()\n"
            "widget1.set_x(5)\n"
            "widget1.set_y(10)\n"
            "widget1.set_width(220)\n"
            "widget1.set_height(30)\n"
            "style.set_bg_opa(lv.OPA.TRANSP)\n"
            "widget1.set_text('0')\n"
            "widget1.add_style(style, 0)\n"
            "data.set_binding_value(widget1, 'text', 'count')\n"
            "data.count = 10\n"
            "# user code\n"
            "print(\"write python code here\")\n"
            "\n");
#else 
    obj_runModule(__pikaMain, "main");
#endif
    return __pikaMain;
}

